### ISSUE TITLE
Request: Tree/Folder view for WebUI

### ISSUE THREAD

**Issue by grichter** [PiSCSI/piscsi#1099]
I have sorted my iso files into a sub folder of images and would like to have a collapsable tree view similar to how zip files are handled in the images section of the WebUI, please? :)

**Comment by rdmark** [comment]
What I'd like to propose here is to generate one table for each directory including the images root, and display them sequentially. Each of them except for the images root is wrapped in a <details> block just like the help text. That structure should degrade gracefully for vintage browsers.

**Comment by rdmark** [comment]
![image](https://user-images.githubusercontent.com/2108467/220031804-76aadc4d-0903-4cc3-8808-ba8945e9924c.png)

Here is a proof of concept. It can be styled better of course, but it does work pretty well!

**Comment by rdmark** [comment]
Code in https://github.com/PiSCSI/piscsi/pull/1102

**Comment by rdmark** [comment]
Thanks for testing! 

The upload dir request: The tricky part here would be to figure out a UI that makes sense, since the Upload form is used for three distinct destinations.

The move button request: This is already possible with the Rename button. If you prefix the target file name with a dir structure the Web UI will create those dirs if needed and move the renamed file there.

**Comment by rdmark** [comment]
![image](https://user-images.githubusercontent.com/2108467/220253956-e7b2e30d-6f54-4169-935d-e5a0d3157a91.png)

How about this for choosing upload subdir in images?

**Comment by grichter** [comment]
Looks like a good place to start

**Comment by fdanapfel** [comment]
> ![image](https://user-images.githubusercontent.com/2108467/220253956-e7b2e30d-6f54-4169-935d-e5a0d3157a91.png)
> 
> How about this for choosing upload subdir in images?

Looks good to me.

**Comment by rdmark** [comment]
PR merged.
